repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: pretty-format-json
    args:
    - "--autofix"
    - "--indent=4"
    - "--no-sort-keys"

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version
  rev: v0.11.12
  hooks:
  # Run the linter
  - id: ruff-check
    args: [ --fix ]
  # Run the formatter
  - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.10
  hooks:
  - id: uv-lock
